import { Document, isScalar, parse, parseDocument, visit } from "yaml";
import { stages, template, type Job, type WorkflowModel } from "./model";

// Turns the model into workflow YAML, and reads workflow YAML back: fully for files GitKit wrote
// (the model rides along in a comment), as a plain-English summary for any other workflow.

const HEADER = "Generated by GitKit Workflow Studio. Edit it visually: GitKit → Workflow Studio.";
const MODEL_PREFIX = "gitkit-model: ";

const ACTIONS = {
  checkout: "actions/checkout@v4",
  node: "actions/setup-node@v4",
  python: "actions/setup-python@v5",
  go: "actions/setup-go@v5",
  buildx: "docker/setup-buildx-action@v3",
  dockerBuild: "docker/build-push-action@v6",
};

type Step = Record<string, unknown>;

function steps(job: Job): Step[] {
  const input = (key: string) => job.inputs[key] ?? "";
  const version = (key: string) => (job.versions.length ? `\${{ matrix.${key} }}` : undefined);
  const checkout: Step = { uses: ACTIONS.checkout };

  switch (job.template) {
    case "node-lint":
    case "node-test":
    case "node-build":
      return [
        checkout,
        {
          uses: ACTIONS.node,
          with: { "node-version": version("node-version") ?? "lts/*", cache: "npm" },
        },
        { run: "npm ci" },
        { run: input("command") },
      ];
    case "python-lint":
      return [
        checkout,
        { uses: ACTIONS.python, with: { "python-version": "3.12" } },
        { run: "pip install ruff" },
        { run: input("command") },
      ];
    case "python-test":
      return [
        checkout,
        { uses: ACTIONS.python, with: { "python-version": version("python-version") ?? "3.12", cache: "pip" } },
        { run: input("install") },
        { run: input("command") },
      ];
    case "go-test":
      return [
        checkout,
        { uses: ACTIONS.go, with: { "go-version": version("go-version") ?? "stable" } },
        { run: input("command") },
      ];
    case "rust-test":
      return [checkout, { run: input("command") }];
    case "docker-build":
      return [
        checkout,
        { uses: ACTIONS.buildx },
        { uses: ACTIONS.dockerBuild, with: { context: input("context"), push: false } },
      ];
    case "custom":
      return [checkout, { run: input("command") }];
  }
}

export function toYaml(model: WorkflowModel): string {
  const t = model.triggers;
  const on: Record<string, unknown> = {};
  if (t.push.enabled || t.tags.enabled) {
    const push: Record<string, unknown> = {};
    if (t.push.enabled && t.push.branches.length) push.branches = t.push.branches;
    // With only a tags filter, GitHub ignores branch pushes, which is what "tags only" means.
    if (t.tags.enabled) push.tags = [t.tags.pattern];
    on.push = Object.keys(push).length ? push : null;
  }
  if (t.pullRequest.enabled)
    on.pull_request = t.pullRequest.branches.length ? { branches: t.pullRequest.branches } : null;
  if (t.schedule.enabled) on.schedule = [{ cron: t.schedule.cron.trim() }];
  if (t.manual) on.workflow_dispatch = null;

  const jobs: Record<string, unknown> = {};
  // Stage order reads top to bottom in the order things run.
  const order = stages(model.jobs).flat();
  for (const id of order) {
    const job = model.jobs.find((j) => j.id === id)!;
    const key = template(job.template).matrixKey;
    const body: Record<string, unknown> = { name: job.name, "runs-on": job.runsOn };
    if (job.needs.length) body.needs = job.needs.length === 1 ? job.needs[0] : job.needs;
    if (key && job.versions.length) body.strategy = { matrix: { [key]: job.versions } };
    body.steps = steps(job);
    jobs[id] = body;
  }

  const workflow: Record<string, unknown> = { name: model.name, on };
  if (model.readOnlyPermissions) workflow.permissions = { contents: "read" };
  if (model.cancelSuperseded) {
    workflow.concurrency = { group: "${{ github.workflow }}-${{ github.ref }}", "cancel-in-progress": true };
  }
  workflow.jobs = jobs;

  const doc = new Document(workflow);
  doc.commentBefore = ` ${HEADER}`;
  // Short lists of plain values read best inline: branches: [main], node-version: ["20", "22"].
  visit(doc, {
    Seq(_, node) {
      if (node.items.every(isScalar)) node.flow = true;
    },
  });
  // null values print as "key:" (e.g. "workflow_dispatch:"), the way people write them by hand.
  const body = doc.toString({ lineWidth: 0, nullStr: "", flowCollectionPadding: false }).replace(/: $/gm, ":");
  return `${body}\n# ${MODEL_PREFIX}${JSON.stringify(model)}\n`;
}

/** The model GitKit embedded in a file it wrote, and whether the file was edited by hand since. */
export function readModel(text: string): { model: WorkflowModel; editedByHand: boolean } | null {
  const line = text.split(/\r?\n/).find((l) => l.startsWith(`# ${MODEL_PREFIX}`));
  if (!line) return null;
  try {
    const model = JSON.parse(line.slice(`# ${MODEL_PREFIX}`.length)) as WorkflowModel;
    return { model, editedByHand: toYaml(model).replace(/\r\n/g, "\n") !== text.replace(/\r\n/g, "\n") };
  } catch {
    return null;
  }
}

export interface Explanation {
  name: string;
  triggers: string[];
  jobs: { id: string; name: string; runsOn: string; needs: string[]; steps: string[]; matrix: string | null }[];
  /** Set when the file couldn't be parsed. */
  error?: string;
}

/** A plain-English reading of any workflow file. */
export function explain(text: string): Explanation {
  const doc = parseDocument(text);
  if (doc.errors.length) return { name: "", triggers: [], jobs: [], error: doc.errors[0].message };
  const data = (parse(text) ?? {}) as Record<string, unknown>;
  // YAML 1.1 reads a bare "on:" key as true; GitHub treats it as "on".
  const on = (data.on ?? data[true as unknown as string]) as unknown;

  return {
    name: typeof data.name === "string" ? data.name : "(unnamed workflow)",
    triggers: describeTriggers(on),
    jobs: Object.entries((data.jobs ?? {}) as Record<string, Record<string, unknown>>).map(([id, job]) => {
      const needs = job?.needs;
      const matrix = (job?.strategy as Record<string, unknown> | undefined)?.matrix as
        Record<string, unknown> | undefined;
      return {
        id,
        name: typeof job?.name === "string" ? job.name : id,
        runsOn: String(job?.["runs-on"] ?? "?"),
        needs: Array.isArray(needs) ? needs.map(String) : needs ? [String(needs)] : [],
        steps: ((job?.steps ?? []) as Record<string, unknown>[]).map((s) =>
          String(s?.name ?? s?.uses ?? (typeof s?.run === "string" ? s.run.split("\n")[0] : "step")),
        ),
        matrix: matrix
          ? Object.entries(matrix)
              .filter(([, v]) => Array.isArray(v))
              .map(([k, v]) => `${k}: ${(v as unknown[]).join(", ")}`)
              .join("; ") || null
          : null,
      };
    }),
  };
}

function describeTriggers(on: unknown): string[] {
  const names: Record<string, string> = {
    push: "on push",
    pull_request: "on pull requests",
    pull_request_target: "on pull requests (with write access)",
    workflow_dispatch: "manually from the Actions tab",
    schedule: "on a schedule",
    release: "when a release is published",
    workflow_call: "when called by another workflow",
  };
  const describeOne = (event: string, config: unknown): string => {
    let text = names[event] ?? `on ${event}`;
    const c = config as Record<string, unknown> | null;
    if (event === "schedule" && Array.isArray(config)) {
      text += ` (${config.map((s) => (s as { cron?: string }).cron).join(", ")})`;
    } else if (c && typeof c === "object") {
      const branches = c.branches as string[] | undefined;
      const tags = c.tags as string[] | undefined;
      if (branches?.length) text += ` to ${branches.join(", ")}`;
      if (tags?.length) text += ` of tags ${tags.join(", ")}`;
    }
    return text;
  };
  if (typeof on === "string") return [describeOne(on, null)];
  if (Array.isArray(on)) return on.map((e) => describeOne(String(e), null));
  if (on && typeof on === "object")
    return Object.entries(on as Record<string, unknown>).map(([e, c]) => describeOne(e, c));
  return [];
}
