import { Document, isScalar, parse, parseDocument, visit } from "yaml";
import { stages, stepsFor, templateKeys, type Job, type Step, type WorkflowModel } from "./model";

// Turns the model into workflow YAML, and reads workflow YAML back: fully for files GitKit wrote
// (the model rides along in a comment), as a plain-English summary for any other workflow.

const HEADER = "Generated by GitKit Workflow Studio. Edit it visually: GitKit → Workflow Studio.";
const MODEL_PREFIX = "gitkit-model: ";

/** The `on:` block for Studio-modelled triggers. */
export function triggersYaml(model: WorkflowModel): unknown {
  if (model.rawOn !== undefined) return model.rawOn;
  const t = model.triggers;
  const on: Record<string, unknown> = {};
  if (t.push.enabled || t.tags.enabled) {
    const push: Record<string, unknown> = {};
    if (t.push.enabled && t.push.branches.length) push.branches = t.push.branches;
    // With only a tags filter, GitHub ignores branch pushes, which is what "tags only" means.
    if (t.tags.enabled) push.tags = [t.tags.pattern];
    on.push = Object.keys(push).length ? push : null;
  }
  if (t.pullRequest.enabled) {
    on.pull_request = t.pullRequest.branches.length ? { branches: t.pullRequest.branches } : null;
  }
  if (t.schedule.enabled) on.schedule = [{ cron: t.schedule.cron.trim() }];
  if (t.manual) on.workflow_dispatch = null;
  return on;
}

function jobYaml(job: Job): Record<string, unknown> {
  const { "runs-on": runsOn, ...extra } = job.extra ?? {};
  const body: Record<string, unknown> = {};
  // Imported jobs without a name keep having none; Studio jobs always say what they are.
  if (job.template !== "steps" || job.name !== job.id) body.name = job.name;
  body["runs-on"] = runsOn ?? job.runsOn;
  if (job.needs.length) body.needs = job.needs.length === 1 ? job.needs[0] : job.needs;
  Object.assign(body, templateKeys(job), extra);
  // A job that calls a reusable workflow (uses:) has no steps or runner of its own.
  if (extra.uses) {
    delete body["runs-on"];
    return body;
  }
  body.steps = stepsFor(job).map(cleanStep);
  return body;
}

/** Drops empty fields a half-filled step would otherwise write out. */
function cleanStep(step: Step): Step {
  const out: Step = {};
  for (const [key, value] of Object.entries(step)) {
    if (value === undefined || value === "") continue;
    if (key === "with" && value && typeof value === "object" && !Object.keys(value).length) continue;
    out[key] = value;
  }
  return out;
}

export function toYaml(model: WorkflowModel): string {
  const jobs: Record<string, unknown> = {};
  // Stage order reads top to bottom in the order things run.
  for (const id of stages(model.jobs).flat()) jobs[id] = jobYaml(model.jobs.find((j) => j.id === id)!);

  const { permissions, concurrency, ...extra } = model.extra ?? {};
  const workflow: Record<string, unknown> = { name: model.name };
  if (extra["run-name"] !== undefined) workflow["run-name"] = extra["run-name"];
  workflow.on = triggersYaml(model);
  if (permissions !== undefined) workflow.permissions = permissions;
  else if (model.readOnlyPermissions) workflow.permissions = { contents: "read" };
  for (const [key, value] of Object.entries(extra)) if (key !== "run-name") workflow[key] = value;
  if (concurrency !== undefined) workflow.concurrency = concurrency;
  else if (model.cancelSuperseded) {
    workflow.concurrency = { group: "${{ github.workflow }}-${{ github.ref }}", "cancel-in-progress": true };
  }
  workflow.jobs = jobs;

  const doc = new Document(workflow);
  doc.commentBefore = ` ${HEADER}`;
  // Short lists of plain values read best inline: branches: [main], node-version: ["20", "22"].
  visit(doc, {
    Seq(_, node) {
      if (node.items.every(isScalar)) node.flow = true;
    },
  });
  // null values print as "key:" (e.g. "workflow_dispatch:"), the way people write them by hand.
  const body = doc.toString({ lineWidth: 0, nullStr: "", flowCollectionPadding: false }).replace(/: $/gm, ":");
  return `${body}\n# ${MODEL_PREFIX}${JSON.stringify(model)}\n`;
}

/** The model GitKit embedded in a file it wrote, and whether the file was edited by hand since. */
export function readModel(text: string): { model: WorkflowModel; editedByHand: boolean } | null {
  const line = text.split(/\r?\n/).find((l) => l.startsWith(`# ${MODEL_PREFIX}`));
  if (!line) return null;
  try {
    const model = JSON.parse(line.slice(`# ${MODEL_PREFIX}`.length)) as WorkflowModel;
    return { model, editedByHand: toYaml(model).replace(/\r\n/g, "\n") !== text.replace(/\r\n/g, "\n") };
  } catch {
    return null;
  }
}

export interface Explanation {
  name: string;
  triggers: string[];
  jobs: { id: string; name: string; runsOn: string; needs: string[]; steps: string[]; matrix: string | null }[];
  /** Set when the file couldn't be parsed. */
  error?: string;
}

/** A plain-English reading of any workflow file. */
export function explain(text: string): Explanation {
  const doc = parseDocument(text);
  if (doc.errors.length) return { name: "", triggers: [], jobs: [], error: doc.errors[0].message };
  const data = (parse(text) ?? {}) as Record<string, unknown>;
  // YAML 1.1 reads a bare "on:" key as true; GitHub treats it as "on".
  const on = (data.on ?? data[true as unknown as string]) as unknown;

  return {
    name: typeof data.name === "string" ? data.name : "(unnamed workflow)",
    triggers: describeTriggers(on),
    jobs: Object.entries((data.jobs ?? {}) as Record<string, Record<string, unknown>>).map(([id, job]) => {
      const needs = job?.needs;
      const matrix = (job?.strategy as Record<string, unknown> | undefined)?.matrix as
        Record<string, unknown> | undefined;
      return {
        id,
        name: typeof job?.name === "string" ? job.name : id,
        runsOn: String(job?.["runs-on"] ?? "?"),
        needs: Array.isArray(needs) ? needs.map(String) : needs ? [String(needs)] : [],
        steps: ((job?.steps ?? []) as Record<string, unknown>[]).map((s) =>
          String(s?.name ?? s?.uses ?? (typeof s?.run === "string" ? s.run.split("\n")[0] : "step")),
        ),
        matrix: matrix
          ? Object.entries(matrix)
              .filter(([, v]) => Array.isArray(v))
              .map(([k, v]) => `${k}: ${(v as unknown[]).join(", ")}`)
              .join("; ") || null
          : null,
      };
    }),
  };
}

function describeTriggers(on: unknown): string[] {
  const names: Record<string, string> = {
    push: "on push",
    pull_request: "on pull requests",
    pull_request_target: "on pull requests (with write access)",
    workflow_dispatch: "manually from the Actions tab",
    schedule: "on a schedule",
    release: "when a release is published",
    workflow_call: "when called by another workflow",
  };
  const describeOne = (event: string, config: unknown): string => {
    let text = names[event] ?? `on ${event}`;
    const c = config as Record<string, unknown> | null;
    if (event === "schedule" && Array.isArray(config)) {
      text += ` (${config.map((s) => (s as { cron?: string }).cron).join(", ")})`;
    } else if (c && typeof c === "object") {
      const branches = c.branches as string[] | undefined;
      const tags = c.tags as string[] | undefined;
      if (branches?.length) text += ` to ${branches.join(", ")}`;
      if (tags?.length) text += ` of tags ${tags.join(", ")}`;
    }
    return text;
  };
  if (typeof on === "string") return [describeOne(on, null)];
  if (Array.isArray(on)) return on.map((e) => describeOne(String(e), null));
  if (on && typeof on === "object")
    return Object.entries(on as Record<string, unknown>).map(([e, c]) => describeOne(e, c));
  return [];
}
